repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: 'v5.7.0'
    hooks:
    -   id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
